services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-nest-auto_rio}
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis-db:
    image: redis:7.2.3
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: >
      --requirepass '${REDIS_PASSWORD:-redispass}'
    volumes:
      - ./redis-db-data:/data
    restart: unless-stopped

volumes:
  postgres-db-data:
  redis-db-data:
