version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - '4000:3000'
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-nest-auto_rio}
      REDIS_HOST: redis-db
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redispass}
    depends_on:
      - postgres-db
      - redis-db
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    command: node dist/src/main.js

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-nest-auto_rio}
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis-db:
    image: redis:7.2.3
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: >
      --requirepass '${REDIS_PASSWORD:-redispass}'
    volumes:
      - ./redis-db-data:/data
    restart: unless-stopped

volumes:
  postgres-db-data:
  redis-db-data:
